apiVersion: v1
kind: Secret
metadata:
  name: feedback-backend-secret
type: Opaque
stringData:
  DATABASE_URL: "postgres://postgres:BitteEinSicheresPasswort123@feedback-analyzer-postgres.cf6ik4w8k20e.eu-central-1.rds.amazonaws.com:5432/feedbackdb"